
  irene = User.create(name: 'Irene', username: 'machine', email: 'maiemail@email.com', password: 'password')
  davis = User.create(name: 'Davis', username: 'doubled', email: 'dmoney@email.com', password: 'password')
  grace = User.create(name: 'Grace', username: 'gsmokes', email: 'weed@email.com', password: 'password')
  tommy = User.create(name: 'Tommy', username: 'zer0gravity', email: 'onfleek@email.com', password: 'password')
  amber = User.create(name: 'Amber', username: 'taiwan', email: 'formosa@email.com', password: 'password')

List.create(name: 'pacific heights', neighborhood: 'Pacific Heights', trash: false, gold: false, user_id: 1)
List.create(name: 'mission', neighborhood: 'Mission', trash: false, gold: false, user_id: 1)
List.create(name: 'nopa', neighborhood: 'Nopa', trash: false, gold: false, user_id: 2)
List.create(name: 'nopa', neighborhood: 'Nopa', trash: false, gold: false, user_id: 4)
List.create(name: 'tenderloin', neighborhood: 'Tenderloin', trash: false, gold: false, user_id: 5)
List.create(name: 'tenderloin', neighborhood: 'Tenderloin', trash: false, gold: false, user_id: 3)
List.create(name: 'nopa', neighborhood: 'Nopa', trash: false, gold: false, user_id: 3)
List.create(name: 'mission', neighborhood: 'mission', trash: false, gold: false, user_id: 4)

Restaurant.create(name: 'El Farolito', cuisine: 'Mexican')
Restaurant.create(name: 'Brenda\'s Meat and Three', cuisine: 'American')
Restaurant.create(name: 'Alexander\'s Steakhouse', cuisine: 'American')
Restaurant.create(name: 'NOPA', cuisine: 'American')
Restaurant.create(name: 'San Tung', cuisine: 'Chinese')
Restaurant.create(name: 'Orenchi', cuisine: 'Japanese')

Selection.create(restaurant_id: 1, list_id: 1)
Selection.create(restaurant_id: 2, list_id: 1)
Selection.create(restaurant_id: 3, list_id: 1)
Selection.create(restaurant_id: 4, list_id: 4)
Selection.create(restaurant_id: 5, list_id: 1)
Selection.create(restaurant_id: 6, list_id: 2)
Selection.create(restaurant_id: 1, list_id: 2)
Selection.create(restaurant_id: 2, list_id: 2)
Selection.create(restaurant_id: 3, list_id: 3)
Selection.create(restaurant_id: 4, list_id: 4)
Selection.create(restaurant_id: 5, list_id: 4)
Selection.create(restaurant_id: 6, list_id: 5)
Selection.create(restaurant_id: 1, list_id: 5)
Selection.create(restaurant_id: 2, list_id: 6)
Selection.create(restaurant_id: 3, list_id: 6)
Selection.create(restaurant_id: 4, list_id: 6)
Selection.create(restaurant_id: 5, list_id: 7)
Selection.create(restaurant_id: 6, list_id: 7)
Selection.create(restaurant_id: 1, list_id: 7)
Selection.create(restaurant_id: 2, list_id: 7)
Selection.create(restaurant_id: 3, list_id: 1)
Selection.create(restaurant_id: 4, list_id: 3)
Selection.create(restaurant_id: 5, list_id: 3)
Selection.create(restaurant_id: 6, list_id: 8)
Selection.create(restaurant_id: 1, list_id: 8)
